<?php

declare(strict_types=1);

date_default_timezone_set("Asia/Manila");

require_once("../config/database.php");
require_once("../../vendor/autoload.php");

use PhpOffice\PhpSpreadsheet\Cell\DataType;
use PhpOffice\PhpSpreadsheet\Spreadsheet;
use PhpOffice\PhpSpreadsheet\Style\Alignment;
use PhpOffice\PhpSpreadsheet\Style\Border;
use PhpOffice\PhpSpreadsheet\Style\Fill;
use PhpOffice\PhpSpreadsheet\Writer\Xlsx;

function isValidDate(string $value): bool
{
    if ($value === "") {
        return true;
    }

    $date = DateTime::createFromFormat("Y-m-d", $value);

    return $date !== false &&
        $date->format("Y-m-d") === $value;
}

try {
    $fromDate = trim((string)($_GET["from_date"] ?? ""));
    $toDate = trim((string)($_GET["to_date"] ?? ""));

    if (!isValidDate($fromDate) || !isValidDate($toDate)) {
        throw new RuntimeException("Invalid inventory export date format.");
    }

    if (
        $fromDate !== "" &&
        $toDate !== "" &&
        $fromDate > $toDate
    ) {
        throw new RuntimeException(
            "The From Date cannot be later than the To Date."
        );
    }

    /*
     * Date-range meaning:
     * Export products that had inventory activity inside the selected period.
     *
     * A product is included when:
     * 1. it had at least one tbl_inventory_history movement in the period; OR
     * 2. the product itself was first created in the period.
     *
     * The quantity/prices/status columns remain the CURRENT inventory values.
     */
    $conditions = [];
    $params = [];

    if ($fromDate !== "" || $toDate !== "") {
        $activityConditions = [];
        $createdConditions = [];

        if ($fromDate !== "") {
            $activityConditions[] = "h.created_at >= :history_from";
            $createdConditions[] = "i.created_at >= :product_from";

            $params[":history_from"] = $fromDate . " 00:00:00";
            $params[":product_from"] = $fromDate . " 00:00:00";
        }

        if ($toDate !== "") {
            $activityConditions[] = "h.created_at < :history_to";
            $createdConditions[] = "i.created_at < :product_to";

            $toExclusive = (new DateTime($toDate))
                ->modify("+1 day")
                ->format("Y-m-d") . " 00:00:00";

            $params[":history_to"] = $toExclusive;
            $params[":product_to"] = $toExclusive;
        }

        $historyWhere = implode(" AND ", $activityConditions);
        $createdWhere = implode(" AND ", $createdConditions);

        $conditions[] = "(
            EXISTS (
                SELECT 1
                FROM tbl_inventory_history h
                WHERE h.product_id = i.product_id
                AND {$historyWhere}
            )
            OR (
                {$createdWhere}
            )
        )";
    }

    $whereSql = count($conditions) > 0
        ? "WHERE " . implode(" AND ", $conditions)
        : "";

    $stmt = $conn->prepare("
        SELECT
            i.product_id,
            i.product_name,
            i.sku,
            i.category,
            i.quantity,
            i.unit_type,
            i.reorder_level,
            i.supplier_price,
            i.selling_price,
            i.expiry_date,
            i.status
        FROM tbl_inv i
        {$whereSql}
        ORDER BY i.product_name ASC, i.product_id ASC
    ");

    $stmt->execute($params);
    $rows = $stmt->fetchAll(PDO::FETCH_ASSOC);

    $spreadsheet = new Spreadsheet();
    $sheet = $spreadsheet->getActiveSheet();

    $spreadsheet->getProperties()
        ->setCreator("HiveSync")
        ->setLastModifiedBy("HiveSync")
        ->setTitle("Inventory Export")
        ->setSubject("HiveSync Inventory")
        ->setDescription("Inventory export generated by HiveSync");

    $sheet->setTitle("Inventory");

    /*
     * Keep a visible date-range summary in the workbook
     * so exported files can easily be verified.
     */
    $sheet->mergeCells("A1:K1");
    $sheet->setCellValue("A1", "HiveSync Inventory Export");

    $sheet->getStyle("A1:K1")->applyFromArray([
        "font" => [
            "bold" => true,
            "size" => 14,
            "color" => ["rgb" => "111827"]
        ],
        "fill" => [
            "fillType" => Fill::FILL_SOLID,
            "startColor" => ["rgb" => "F4B400"]
        ],
        "alignment" => [
            "horizontal" => Alignment::HORIZONTAL_CENTER,
            "vertical" => Alignment::VERTICAL_CENTER
        ]
    ]);

    $sheet->getRowDimension(1)->setRowHeight(26);

    $sheet->mergeCells("A2:K2");

    if ($fromDate !== "" && $toDate !== "") {
        $periodLabel =
            "Inventory activity period: " .
            date("M d, Y", strtotime($fromDate)) .
            " to " .
            date("M d, Y", strtotime($toDate));
    } elseif ($fromDate !== "") {
        $periodLabel =
            "Inventory activity from: " .
            date("M d, Y", strtotime($fromDate));
    } elseif ($toDate !== "") {
        $periodLabel =
            "Inventory activity through: " .
            date("M d, Y", strtotime($toDate));
    } else {
        $periodLabel = "Inventory activity period: All dates";
    }

    $sheet->setCellValue("A2", $periodLabel);

    $sheet->getStyle("A2:K2")->applyFromArray([
        "font" => [
            "italic" => true,
            "color" => ["rgb" => "6B7280"]
        ],
        "alignment" => [
            "horizontal" => Alignment::HORIZONTAL_CENTER,
            "vertical" => Alignment::VERTICAL_CENTER
        ]
    ]);

    $headers = [
        "Product ID",
        "Product Name",
        "SKU",
        "Category",
        "Current Quantity",
        "Unit Type",
        "Reorder Level",
        "Supplier Price",
        "Selling Price",
        "Expiry Date",
        "Status"
    ];

    $headerRow = 4;
    $sheet->fromArray($headers, null, "A{$headerRow}");

    $sheet->getStyle("A{$headerRow}:K{$headerRow}")->applyFromArray([
        "font" => [
            "bold" => true,
            "color" => ["rgb" => "111827"]
        ],
        "fill" => [
            "fillType" => Fill::FILL_SOLID,
            "startColor" => ["rgb" => "F4B400"]
        ],
        "alignment" => [
            "horizontal" => Alignment::HORIZONTAL_CENTER,
            "vertical" => Alignment::VERTICAL_CENTER
        ],
        "borders" => [
            "allBorders" => [
                "borderStyle" => Border::BORDER_THIN,
                "color" => ["rgb" => "D1D5DB"]
            ]
        ]
    ]);

    $sheet->getRowDimension($headerRow)->setRowHeight(24);

    $rowNumber = $headerRow + 1;

    foreach ($rows as $row) {
        $sheet->setCellValue(
            "A{$rowNumber}",
            (int)$row["product_id"]
        );

        $sheet->setCellValue(
            "B{$rowNumber}",
            (string)($row["product_name"] ?? "")
        );

        $sheet->setCellValueExplicit(
            "C{$rowNumber}",
            (string)($row["sku"] ?? ""),
            DataType::TYPE_STRING
        );

        $sheet->setCellValue(
            "D{$rowNumber}",
            (string)($row["category"] ?? "")
        );

        $sheet->setCellValue(
            "E{$rowNumber}",
            (float)($row["quantity"] ?? 0)
        );

        $sheet->setCellValue(
            "F{$rowNumber}",
            (string)($row["unit_type"] ?? "")
        );

        $sheet->setCellValue(
            "G{$rowNumber}",
            (float)($row["reorder_level"] ?? 0)
        );

        $sheet->setCellValue(
            "H{$rowNumber}",
            (float)($row["supplier_price"] ?? 0)
        );

        $sheet->setCellValue(
            "I{$rowNumber}",
            (float)($row["selling_price"] ?? 0)
        );

        $sheet->setCellValue(
            "J{$rowNumber}",
            (string)($row["expiry_date"] ?? "")
        );

        $sheet->setCellValue(
            "K{$rowNumber}",
            (string)($row["status"] ?? "")
        );

        $rowNumber++;
    }

    if (count($rows) === 0) {
        $sheet->mergeCells("A5:K5");
        $sheet->setCellValue(
            "A5",
            "No inventory products had activity during the selected date range."
        );

        $sheet->getStyle("A5:K5")
            ->getAlignment()
            ->setHorizontal(Alignment::HORIZONTAL_CENTER);

        $sheet->getStyle("A5:K5")
            ->getFont()
            ->setItalic(true);

        $lastRow = 5;
    } else {
        $lastRow = $rowNumber - 1;

        $sheet->getStyle("A5:K{$lastRow}")
            ->getAlignment()
            ->setVertical(Alignment::VERTICAL_CENTER);

        $sheet->getStyle("A5:A{$lastRow}")
            ->getAlignment()
            ->setHorizontal(Alignment::HORIZONTAL_CENTER);

        $sheet->getStyle("E5:G{$lastRow}")
            ->getAlignment()
            ->setHorizontal(Alignment::HORIZONTAL_CENTER);

        $sheet->getStyle("J5:K{$lastRow}")
            ->getAlignment()
            ->setHorizontal(Alignment::HORIZONTAL_CENTER);

        $sheet->getStyle("H5:I{$lastRow}")
            ->getNumberFormat()
            ->setFormatCode('₱#,##0.00');
    }

    $sheet->getStyle("A{$headerRow}:K{$lastRow}")
        ->getBorders()
        ->getAllBorders()
        ->setBorderStyle(Border::BORDER_THIN);

    $sheet->freezePane("A5");
    $sheet->setAutoFilter(
        "A{$headerRow}:K{$lastRow}"
    );

    $columnWidths = [
        "A" => 12,
        "B" => 28,
        "C" => 18,
        "D" => 20,
        "E" => 16,
        "F" => 14,
        "G" => 14,
        "H" => 16,
        "I" => 16,
        "J" => 15,
        "K" => 20
    ];

    foreach ($columnWidths as $column => $width) {
        $sheet->getColumnDimension($column)
            ->setWidth($width);
    }

    $rangePart = "";

    if ($fromDate !== "" || $toDate !== "") {
        $rangePart =
            "_" .
            ($fromDate !== "" ? $fromDate : "START") .
            "_to_" .
            ($toDate !== "" ? $toDate : "END");
    }

    $fileName =
        "HiveSync_Inventory" .
        $rangePart .
        "_" .
        date("Y-m-d_His") .
        ".xlsx";

    if (ob_get_length()) {
        ob_end_clean();
    }

    header(
        "Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
    );

    header(
        'Content-Disposition: attachment; filename="' .
        $fileName .
        '"'
    );

    header("Cache-Control: max-age=0");

    $writer = new Xlsx($spreadsheet);
    $writer->save("php://output");

    $spreadsheet->disconnectWorksheets();

    exit;
} catch (Throwable $error) {
    error_log(
        "inventory_management/export_inventory.php: " .
        $error->getMessage()
    );

    http_response_code(500);
    header("Content-Type: text/plain; charset=utf-8");

    echo "Unable to export inventory Excel file. " .
        $error->getMessage();

    exit;
}
